const SOCKETIO_SERVER_HOST = process.env.SOCKETIO_SERVER_HOST;
const SOCKETIO_MAIN_DATA_SERVER_HOST =
  process.env.SOCKETIO_MAIN_DATA_SERVER_HOST;

module.exports = { SOCKETIO_SERVER_HOST, SOCKETIO_MAIN_DATA_SERVER_HOST };
