const moment = require("moment");
const time = moment().format("YYYY-MM-DD T HH:mm:ss");

const deviceList = {
  fan1: "fan",
  fan2: "fan",
  fna3: "fan",
  shutter1: "shutter",
  shutter2: "shutter",
  shutter3: "shutter",
  shutter4: "shutter",
  shutter5: "shutter",
  shutter6: "shutter",
  shutter7: "shutter",
  nutrient: "nutrient",
};

const emergency = [
  {
    bedId: 5,
    device: "fan",
    active: "stop",
    deviceName: "fan1",
    dev_data: [],
    datetime: time,
  },
  {
    bedId: 5,
    device: "fan",
    active: "stop",
    deviceName: "fan2",
    dev_data: [],
    datetime: time,
  },
  {
    bedId: 5,
    device: "fan",
    active: "stop",
    deviceName: "fan3",
    dev_data: [],
    datetime: time,
  },
  {
    bedId: 5,
    device: "shutter",
    active: "stop",
    deviceName: "shutter1",
    dev_data: [],
    datetime: time,
  },
  {
    bedId: 5,
    device: "shutter",
    active: "stop",
    deviceName: "shutter2",
    dev_data: [],
    datetime: time,
  },
  {
    bedId: 5,
    device: "shutter",
    active: "stop",
    deviceName: "shutter3",
    dev_data: [],
    datetime: time,
  },
  {
    bedId: 5,
    device: "shutter",
    active: "stop",
    deviceName: "shutter4",
    dev_data: [],
    datetime: time,
  },
  {
    bedId: 5,
    device: "shutter",
    active: "stop",
    deviceName: "shutter5",
    dev_data: [],
    datetime: time,
  },
  {
    bedId: 5,
    device: "shutter",
    active: "stop",
    deviceName: "shutter6",
    dev_data: [],
    datetime: time,
  },
  {
    bedId: 5,
    device: "shutter",
    active: "stop",
    deviceName: "shutter7",
    dev_data: [],
    datetime: time,
  },
];

const activeList = {
  open: "open",
  close: "close",
  on: "on",
  stop: "stop",
};

const nutrient = {
  waterOrFertilizer: {
    setWaterDetail_1: {
      modbus_address: "00016",
      description: "0",
      property: "write",
    },

    setFertilizerDetail_2: {
      modbus_address: "00017",
      description: "1",
      property: "write",
    },
  },
  use: {
    useDetail_1: {
      modbus_address: "00048",
      description: "1",
      property: "write",
    },

    useDetail_2: {
      modbus_address: "00049",
      description: "1",
      property: "write",
    },
  },
  notUse: {
    notUseDetail_1: {
      modbus_address: "00048",
      description: "0",
      property: "write",
    },
    notUseDetail_2: {
      modbus_address: "00049",
      description: "0",
      property: "write",
    },
  },
  useLine: {
    line_1: { modbus_address: "00160", description: "1", property: "write" },
    line_2: { modbus_address: "00161", description: "1", property: "write" },
    line_3: { modbus_address: "00162", description: "1", property: "write" },
    line_4: { modbus_address: "00163", description: "1", property: "write" },
  },

  notUseLine: {
    line_1: { modbus_address: "00160", description: "0", property: "write" },
    line_2: { modbus_address: "00161", description: "0", property: "write" },
    line_3: { modbus_address: "00162", description: "0", property: "write" },
    line_4: { modbus_address: "00163", description: "0", property: "write" },
  },
  act: {
    run: { modbus_address: "00560", description: "1", property: "write" },
    stop: { modbus_address: "00561", description: "1", property: "write" },
  },

  state: {
    lackWater: { modbus_address: "10080", description: "", property: "read" },
    running: { modbus_address: "10081", description: "", property: "read" },
    mainPump: { modbus_address: "10082", description: "", property: "read" },
    pump: { modbus_address: "10083", description: "", property: "read" },
    run: { modbus_address: "10096", description: "", property: "read" },
    stop: { modbus_address: "10100", description: "", property: "read" },
  },
};

const readNutrient = {
  plcCurrentTime: [
    { modbus_address: "40210", description: "", property: "read" },
    { modbus_address: "40211", description: "", property: "read" },
    { modbus_address: "40212", description: "", property: "read" },
    { modbus_address: "40213", description: "", property: "read" },
    { modbus_address: "40214", description: "", property: "read" },
    { modbus_address: "40215", description: "", property: "read" },
    { modbus_address: "40216", description: "", property: "read" },
  ],
};

const supply = {
  list: {
    line_1: { modbus_address: "44800", description: "", property: "read" },
    line_2: { modbus_address: "44801", description: "", property: "read" },
    line_3: { modbus_address: "44802", description: "", property: "read" },
    line_4: { modbus_address: "44803", description: "", property: "read" },
  },
};

const readNutrientDataDigitalAndAnalog = {
  list: [
    { modbus_address: "1", description: "", property: "read" },
    { modbus_address: "16", description: "", property: "read" },
    { modbus_address: "17", description: "", property: "read" },
    { modbus_address: "18", description: "", property: "read" },
    { modbus_address: "19", description: "", property: "read" },
    { modbus_address: "20", description: "", property: "read" },
    { modbus_address: "21", description: "", property: "read" },
    { modbus_address: "22", description: "", property: "read" },
    { modbus_address: "23", description: "", property: "read" },
    { modbus_address: "24", description: "", property: "read" },
    { modbus_address: "25", description: "", property: "read" },
    { modbus_address: "26", description: "", property: "read" },
    { modbus_address: "27", description: "", property: "read" },
    { modbus_address: "28", description: "", property: "read" },
    { modbus_address: "29", description: "", property: "read" },
    { modbus_address: "30", description: "", property: "read" },
    { modbus_address: "31", description: "", property: "read" },
    { modbus_address: "32", description: "", property: "read" },
    { modbus_address: "33", description: "", property: "read" },
    { modbus_address: "34", description: "", property: "read" },
    { modbus_address: "35", description: "", property: "read" },
    { modbus_address: "36", description: "", property: "read" },
    { modbus_address: "37", description: "", property: "read" },
    { modbus_address: "38", description: "", property: "read" },
    { modbus_address: "39", description: "", property: "read" },
    { modbus_address: "48", description: "", property: "read" },
    { modbus_address: "49", description: "", property: "read" },
    { modbus_address: "50", description: "", property: "read" },
    { modbus_address: "51", description: "", property: "read" },
    { modbus_address: "52", description: "", property: "read" },
    { modbus_address: "53", description: "", property: "read" },
    { modbus_address: "54", description: "", property: "read" },
    { modbus_address: "55", description: "", property: "read" },
    { modbus_address: "56", description: "", property: "read" },
    { modbus_address: "57", description: "", property: "read" },
    { modbus_address: "58", description: "", property: "read" },
    { modbus_address: "59", description: "", property: "read" },
    { modbus_address: "60", description: "", property: "read" },
    { modbus_address: "61", description: "", property: "read" },
    { modbus_address: "62", description: "", property: "read" },
    { modbus_address: "63", description: "", property: "read" },
    { modbus_address: "64", description: "", property: "read" },
    { modbus_address: "65", description: "", property: "read" },
    { modbus_address: "66", description: "", property: "read" },
    { modbus_address: "67", description: "", property: "read" },
    { modbus_address: "68", description: "", property: "read" },
    { modbus_address: "69", description: "", property: "read" },
    { modbus_address: "70", description: "", property: "read" },
    { modbus_address: "80", description: "", property: "read" },
    { modbus_address: "160", description: "", property: "read" },
    { modbus_address: "161", description: "", property: "read" },
    { modbus_address: "162", description: "", property: "read" },
    { modbus_address: "163", description: "", property: "read" },
    { modbus_address: "164", description: "", property: "read" },
    { modbus_address: "165", description: "", property: "read" },
    { modbus_address: "166", description: "", property: "read" },
    { modbus_address: "167", description: "", property: "read" },
    { modbus_address: "168", description: "", property: "read" },
    { modbus_address: "169", description: "", property: "read" },
    { modbus_address: "176", description: "", property: "read" },
    { modbus_address: "177", description: "", property: "read" },
    { modbus_address: "178", description: "", property: "read" },
    { modbus_address: "179", description: "", property: "read" },
    { modbus_address: "180", description: "", property: "read" },
    { modbus_address: "181", description: "", property: "read" },
    { modbus_address: "182", description: "", property: "read" },
    { modbus_address: "183", description: "", property: "read" },
    { modbus_address: "184", description: "", property: "read" },
    { modbus_address: "185", description: "", property: "read" },
    { modbus_address: "192", description: "", property: "read" },
    { modbus_address: "193", description: "", property: "read" },
    { modbus_address: "194", description: "", property: "read" },
    { modbus_address: "195", description: "", property: "read" },
    { modbus_address: "196", description: "", property: "read" },
    { modbus_address: "197", description: "", property: "read" },
    { modbus_address: "198", description: "", property: "read" },
    { modbus_address: "199", description: "", property: "read" },
    { modbus_address: "200", description: "", property: "read" },
    { modbus_address: "201", description: "", property: "read" },
    { modbus_address: "208", description: "", property: "read" },
    { modbus_address: "209", description: "", property: "read" },
    { modbus_address: "210", description: "", property: "read" },
    { modbus_address: "211", description: "", property: "read" },
    { modbus_address: "212", description: "", property: "read" },
    { modbus_address: "213", description: "", property: "read" },
    { modbus_address: "214", description: "", property: "read" },
    { modbus_address: "215", description: "", property: "read" },
    { modbus_address: "216", description: "", property: "read" },
    { modbus_address: "217", description: "", property: "read" },
    { modbus_address: "224", description: "", property: "read" },
    { modbus_address: "225", description: "", property: "read" },
    { modbus_address: "226", description: "", property: "read" },
    { modbus_address: "227", description: "", property: "read" },
    { modbus_address: "228", description: "", property: "read" },
    { modbus_address: "229", description: "", property: "read" },
    { modbus_address: "230", description: "", property: "read" },
    { modbus_address: "231", description: "", property: "read" },
    { modbus_address: "232", description: "", property: "read" },
    { modbus_address: "233", description: "", property: "read" },
    { modbus_address: "240", description: "", property: "read" },
    { modbus_address: "241", description: "", property: "read" },
    { modbus_address: "242", description: "", property: "read" },
    { modbus_address: "243", description: "", property: "read" },
    { modbus_address: "244", description: "", property: "read" },
    { modbus_address: "245", description: "", property: "read" },
    { modbus_address: "246", description: "", property: "read" },
    { modbus_address: "247", description: "", property: "read" },
    { modbus_address: "248", description: "", property: "read" },
    { modbus_address: "249", description: "", property: "read" },
    { modbus_address: "256", description: "", property: "read" },
    { modbus_address: "257", description: "", property: "read" },
    { modbus_address: "258", description: "", property: "read" },
    { modbus_address: "259", description: "", property: "read" },
    { modbus_address: "260", description: "", property: "read" },
    { modbus_address: "261", description: "", property: "read" },
    { modbus_address: "262", description: "", property: "read" },
    { modbus_address: "263", description: "", property: "read" },
    { modbus_address: "264", description: "", property: "read" },
    { modbus_address: "265", description: "", property: "read" },
    { modbus_address: "272", description: "", property: "read" },
    { modbus_address: "273", description: "", property: "read" },
    { modbus_address: "274", description: "", property: "read" },
    { modbus_address: "275", description: "", property: "read" },
    { modbus_address: "276", description: "", property: "read" },
    { modbus_address: "277", description: "", property: "read" },
    { modbus_address: "278", description: "", property: "read" },
    { modbus_address: "279", description: "", property: "read" },
    { modbus_address: "280", description: "", property: "read" },
    { modbus_address: "281", description: "", property: "read" },
    { modbus_address: "288", description: "", property: "read" },
    { modbus_address: "289", description: "", property: "read" },
    { modbus_address: "290", description: "", property: "read" },
    { modbus_address: "291", description: "", property: "read" },
    { modbus_address: "292", description: "", property: "read" },
    { modbus_address: "293", description: "", property: "read" },
    { modbus_address: "294", description: "", property: "read" },
    { modbus_address: "295", description: "", property: "read" },
    { modbus_address: "296", description: "", property: "read" },
    { modbus_address: "297", description: "", property: "read" },
    { modbus_address: "304", description: "", property: "read" },
    { modbus_address: "305", description: "", property: "read" },
    { modbus_address: "306", description: "", property: "read" },
    { modbus_address: "307", description: "", property: "read" },
    { modbus_address: "308", description: "", property: "read" },
    { modbus_address: "309", description: "", property: "read" },
    { modbus_address: "310", description: "", property: "read" },
    { modbus_address: "311", description: "", property: "read" },
    { modbus_address: "312", description: "", property: "read" },
    { modbus_address: "313", description: "", property: "read" },
    { modbus_address: "320", description: "", property: "read" },
    { modbus_address: "321", description: "", property: "read" },
    { modbus_address: "322", description: "", property: "read" },
    { modbus_address: "323", description: "", property: "read" },
    { modbus_address: "324", description: "", property: "read" },
    { modbus_address: "325", description: "", property: "read" },
    { modbus_address: "326", description: "", property: "read" },
    { modbus_address: "327", description: "", property: "read" },
    { modbus_address: "328", description: "", property: "read" },
    { modbus_address: "329", description: "", property: "read" },
    { modbus_address: "336", description: "", property: "read" },
    { modbus_address: "337", description: "", property: "read" },
    { modbus_address: "338", description: "", property: "read" },
    { modbus_address: "339", description: "", property: "read" },
    { modbus_address: "340", description: "", property: "read" },
    { modbus_address: "341", description: "", property: "read" },
    { modbus_address: "342", description: "", property: "read" },
    { modbus_address: "343", description: "", property: "read" },
    { modbus_address: "344", description: "", property: "read" },
    { modbus_address: "345", description: "", property: "read" },
    { modbus_address: "352", description: "", property: "read" },
    { modbus_address: "353", description: "", property: "read" },
    { modbus_address: "354", description: "", property: "read" },
    { modbus_address: "355", description: "", property: "read" },
    { modbus_address: "356", description: "", property: "read" },
    { modbus_address: "357", description: "", property: "read" },
    { modbus_address: "358", description: "", property: "read" },
    { modbus_address: "359", description: "", property: "read" },
    { modbus_address: "360", description: "", property: "read" },
    { modbus_address: "361", description: "", property: "read" },
    { modbus_address: "368", description: "", property: "read" },
    { modbus_address: "369", description: "", property: "read" },
    { modbus_address: "370", description: "", property: "read" },
    { modbus_address: "371", description: "", property: "read" },
    { modbus_address: "372", description: "", property: "read" },
    { modbus_address: "373", description: "", property: "read" },
    { modbus_address: "374", description: "", property: "read" },
    { modbus_address: "375", description: "", property: "read" },
    { modbus_address: "376", description: "", property: "read" },
    { modbus_address: "377", description: "", property: "read" },
    { modbus_address: "384", description: "", property: "read" },
    { modbus_address: "385", description: "", property: "read" },
    { modbus_address: "386", description: "", property: "read" },
    { modbus_address: "387", description: "", property: "read" },
    { modbus_address: "388", description: "", property: "read" },
    { modbus_address: "389", description: "", property: "read" },
    { modbus_address: "390", description: "", property: "read" },
    { modbus_address: "391", description: "", property: "read" },
    { modbus_address: "392", description: "", property: "read" },
    { modbus_address: "393", description: "", property: "read" },
    { modbus_address: "400", description: "", property: "read" },
    { modbus_address: "401", description: "", property: "read" },
    { modbus_address: "402", description: "", property: "read" },
    { modbus_address: "403", description: "", property: "read" },
    { modbus_address: "404", description: "", property: "read" },
    { modbus_address: "405", description: "", property: "read" },
    { modbus_address: "406", description: "", property: "read" },
    { modbus_address: "407", description: "", property: "read" },
    { modbus_address: "408", description: "", property: "read" },
    { modbus_address: "409", description: "", property: "read" },
    { modbus_address: "416", description: "", property: "read" },
    { modbus_address: "417", description: "", property: "read" },
    { modbus_address: "418", description: "", property: "read" },
    { modbus_address: "419", description: "", property: "read" },
    { modbus_address: "420", description: "", property: "read" },
    { modbus_address: "421", description: "", property: "read" },
    { modbus_address: "422", description: "", property: "read" },
    { modbus_address: "423", description: "", property: "read" },
    { modbus_address: "424", description: "", property: "read" },
    { modbus_address: "425", description: "", property: "read" },
    { modbus_address: "432", description: "", property: "read" },
    { modbus_address: "433", description: "", property: "read" },
    { modbus_address: "434", description: "", property: "read" },
    { modbus_address: "435", description: "", property: "read" },
    { modbus_address: "436", description: "", property: "read" },
    { modbus_address: "437", description: "", property: "read" },
    { modbus_address: "438", description: "", property: "read" },
    { modbus_address: "439", description: "", property: "read" },
    { modbus_address: "440", description: "", property: "read" },
    { modbus_address: "441", description: "", property: "read" },
    { modbus_address: "448", description: "", property: "read" },
    { modbus_address: "449", description: "", property: "read" },
    { modbus_address: "450", description: "", property: "read" },
    { modbus_address: "451", description: "", property: "read" },
    { modbus_address: "452", description: "", property: "read" },
    { modbus_address: "453", description: "", property: "read" },
    { modbus_address: "454", description: "", property: "read" },
    { modbus_address: "455", description: "", property: "read" },
    { modbus_address: "456", description: "", property: "read" },
    { modbus_address: "457", description: "", property: "read" },
    { modbus_address: "464", description: "", property: "read" },
    { modbus_address: "465", description: "", property: "read" },
    { modbus_address: "466", description: "", property: "read" },
    { modbus_address: "467", description: "", property: "read" },
    { modbus_address: "468", description: "", property: "read" },
    { modbus_address: "469", description: "", property: "read" },
    { modbus_address: "470", description: "", property: "read" },
    { modbus_address: "471", description: "", property: "read" },
    { modbus_address: "472", description: "", property: "read" },
    { modbus_address: "473", description: "", property: "read" },
    { modbus_address: "480", description: "", property: "read" },
    { modbus_address: "481", description: "", property: "read" },
    { modbus_address: "482", description: "", property: "read" },
    { modbus_address: "483", description: "", property: "read" },
    { modbus_address: "484", description: "", property: "read" },
    { modbus_address: "485", description: "", property: "read" },
    { modbus_address: "486", description: "", property: "read" },
    { modbus_address: "487", description: "", property: "read" },
    { modbus_address: "488", description: "", property: "read" },
    { modbus_address: "489", description: "", property: "read" },
    { modbus_address: "512", description: "", property: "read" },
    { modbus_address: "513", description: "", property: "read" },
    { modbus_address: "514", description: "", property: "read" },
    { modbus_address: "515", description: "", property: "read" },
    { modbus_address: "516", description: "", property: "read" },
    { modbus_address: "517", description: "", property: "read" },
    { modbus_address: "518", description: "", property: "read" },
    { modbus_address: "519", description: "", property: "read" },
    { modbus_address: "520", description: "", property: "read" },
    { modbus_address: "521", description: "", property: "read" },
    { modbus_address: "560", description: "", property: "read" },
    { modbus_address: "561", description: "", property: "read" },
    { modbus_address: "1080", description: "", property: "read" },
    { modbus_address: "1081", description: "", property: "read" },
    { modbus_address: "1082", description: "", property: "read" },
    { modbus_address: "1083", description: "", property: "read" },
    { modbus_address: "1084", description: "", property: "read" },
    { modbus_address: "1085", description: "", property: "read" },
    { modbus_address: "1086", description: "", property: "read" },
    { modbus_address: "1087", description: "", property: "read" },
    { modbus_address: "10256", description: "", property: "read" },
    { modbus_address: "10257", description: "", property: "read" },
    { modbus_address: "10258", description: "", property: "read" },
    { modbus_address: "10259", description: "", property: "read" },
    { modbus_address: "10260", description: "", property: "read" },
    { modbus_address: "10261", description: "", property: "read" },
    { modbus_address: "10262", description: "", property: "read" },
    { modbus_address: "10263", description: "", property: "read" },
    { modbus_address: "10264", description: "", property: "read" },
    { modbus_address: "10265", description: "", property: "read" },
    { modbus_address: "10266", description: "", property: "read" },
    { modbus_address: "10267", description: "", property: "read" },
    { modbus_address: "10268", description: "", property: "read" },
    { modbus_address: "10269", description: "", property: "read" },
    { modbus_address: "10270", description: "", property: "read" },
    { modbus_address: "10271", description: "", property: "read" },
    { modbus_address: "10272", description: "", property: "read" },
    { modbus_address: "10273", description: "", property: "read" },

    { modbus_address: "40000", description: "", property: "read" },
    { modbus_address: "40001", description: "", property: "read" },
    { modbus_address: "40210", description: "", property: "read" },
    { modbus_address: "40211", description: "", property: "read" },
    { modbus_address: "40212", description: "", property: "read" },
    { modbus_address: "40213", description: "", property: "read" },
    { modbus_address: "40214", description: "", property: "read" },
    { modbus_address: "40215", description: "", property: "read" },
    { modbus_address: "40216", description: "", property: "read" },
    { modbus_address: "41252", description: "", property: "read" },
    { modbus_address: "41501", description: "", property: "read" },
    { modbus_address: "41502", description: "", property: "read" },
    { modbus_address: "41503", description: "", property: "read" },
    { modbus_address: "41600", description: "", property: "read" },
    { modbus_address: "41601", description: "", property: "read" },
    { modbus_address: "41602", description: "", property: "read" },
    { modbus_address: "41603", description: "", property: "read" },
    { modbus_address: "41800", description: "", property: "read" },
    { modbus_address: "41801", description: "", property: "read" },
    { modbus_address: "41802", description: "", property: "read" },
    { modbus_address: "41803", description: "", property: "read" },
    { modbus_address: "41810", description: "", property: "read" },
    { modbus_address: "41811", description: "", property: "read" },
    { modbus_address: "44100", description: "", property: "read" },
    { modbus_address: "44101", description: "", property: "read" },
    { modbus_address: "44102", description: "", property: "read" },
    { modbus_address: "44103", description: "", property: "read" },
    { modbus_address: "44104", description: "", property: "read" },
    { modbus_address: "44105", description: "", property: "read" },
    { modbus_address: "44106", description: "", property: "read" },
    { modbus_address: "44111", description: "", property: "read" },
    { modbus_address: "44112", description: "", property: "read" },
    { modbus_address: "44113", description: "", property: "read" },
    { modbus_address: "44114", description: "", property: "read" },
    { modbus_address: "44115", description: "", property: "read" },
    { modbus_address: "44116", description: "", property: "read" },
    { modbus_address: "44117", description: "", property: "read" },
    { modbus_address: "44150", description: "", property: "read" },
    { modbus_address: "44151", description: "", property: "read" },
    { modbus_address: "44152", description: "", property: "read" },
    { modbus_address: "44153", description: "", property: "read" },
    { modbus_address: "44200", description: "", property: "read" },
    { modbus_address: "44201", description: "", property: "read" },
    { modbus_address: "44202", description: "", property: "read" },
    { modbus_address: "44203", description: "", property: "read" },
    { modbus_address: "44204", description: "", property: "read" },
    { modbus_address: "44205", description: "", property: "read" },
    { modbus_address: "44206", description: "", property: "read" },
    { modbus_address: "44207", description: "", property: "read" },
    { modbus_address: "44208", description: "", property: "read" },
    { modbus_address: "44209", description: "", property: "read" },
    { modbus_address: "44210", description: "", property: "read" },
    { modbus_address: "44211", description: "", property: "read" },
    { modbus_address: "44212", description: "", property: "read" },
    { modbus_address: "44213", description: "", property: "read" },
    { modbus_address: "44214", description: "", property: "read" },
    { modbus_address: "44215", description: "", property: "read" },
    { modbus_address: "44216", description: "", property: "read" },
    { modbus_address: "44217", description: "", property: "read" },
    { modbus_address: "44218", description: "", property: "read" },
    { modbus_address: "44219", description: "", property: "read" },
    { modbus_address: "44220", description: "", property: "read" },
    { modbus_address: "44221", description: "", property: "read" },
    { modbus_address: "44222", description: "", property: "read" },
    { modbus_address: "44223", description: "", property: "read" },
    { modbus_address: "44224", description: "", property: "read" },
    { modbus_address: "44225", description: "", property: "read" },
    { modbus_address: "44226", description: "", property: "read" },
    { modbus_address: "44227", description: "", property: "read" },
    { modbus_address: "44228", description: "", property: "read" },
    { modbus_address: "44229", description: "", property: "read" },
    { modbus_address: "44230", description: "", property: "read" },
    { modbus_address: "44231", description: "", property: "read" },
    { modbus_address: "44232", description: "", property: "read" },
    { modbus_address: "44233", description: "", property: "read" },
    { modbus_address: "44234", description: "", property: "read" },
    { modbus_address: "44235", description: "", property: "read" },
    { modbus_address: "44236", description: "", property: "read" },
    { modbus_address: "44237", description: "", property: "read" },
    { modbus_address: "44238", description: "", property: "read" },
    { modbus_address: "44239", description: "", property: "read" },
    { modbus_address: "44240", description: "", property: "read" },
    { modbus_address: "44241", description: "", property: "read" },
    { modbus_address: "44242", description: "", property: "read" },
    { modbus_address: "44243", description: "", property: "read" },
    { modbus_address: "44244", description: "", property: "read" },
    { modbus_address: "44245", description: "", property: "read" },
    { modbus_address: "44246", description: "", property: "read" },
    { modbus_address: "44247", description: "", property: "read" },
    { modbus_address: "44300", description: "", property: "read" },
    { modbus_address: "44301", description: "", property: "read" },
    { modbus_address: "44302", description: "", property: "read" },
    { modbus_address: "44303", description: "", property: "read" },
    { modbus_address: "44304", description: "", property: "read" },
    { modbus_address: "44305", description: "", property: "read" },
    { modbus_address: "44306", description: "", property: "read" },
    { modbus_address: "44307", description: "", property: "read" },
    { modbus_address: "44340", description: "", property: "read" },
    { modbus_address: "44341", description: "", property: "read" },
    { modbus_address: "44342", description: "", property: "read" },
    { modbus_address: "44343", description: "", property: "read" },
    { modbus_address: "44360", description: "", property: "read" },
    { modbus_address: "44361", description: "", property: "read" },
    { modbus_address: "44362", description: "", property: "read" },
    { modbus_address: "44363", description: "", property: "read" },
    { modbus_address: "44380", description: "", property: "read" },
    { modbus_address: "44381", description: "", property: "read" },
    { modbus_address: "44382", description: "", property: "read" },
    { modbus_address: "44383", description: "", property: "read" },
    { modbus_address: "44400", description: "", property: "read" },
    { modbus_address: "44520", description: "", property: "read" },
    { modbus_address: "44521", description: "", property: "read" },
    { modbus_address: "44522", description: "", property: "read" },
    { modbus_address: "44523", description: "", property: "read" },
    { modbus_address: "44524", description: "", property: "read" },
    { modbus_address: "44525", description: "", property: "read" },
    { modbus_address: "44526", description: "", property: "read" },
    { modbus_address: "44527", description: "", property: "read" },
    { modbus_address: "44560", description: "", property: "read" },
    { modbus_address: "44561", description: "", property: "read" },
    { modbus_address: "44562", description: "", property: "read" },
    { modbus_address: "44563", description: "", property: "read" },
    { modbus_address: "44564", description: "", property: "read" },
    { modbus_address: "44565", description: "", property: "read" },
    { modbus_address: "44566", description: "", property: "read" },
    { modbus_address: "44567", description: "", property: "read" },
    { modbus_address: "44600", description: "", property: "read" },
    { modbus_address: "44601", description: "", property: "read" },
    { modbus_address: "44602", description: "", property: "read" },
    { modbus_address: "44603", description: "", property: "read" },
    { modbus_address: "44604", description: "", property: "read" },
    { modbus_address: "44605", description: "", property: "read" },
    { modbus_address: "44606", description: "", property: "read" },
    { modbus_address: "44607", description: "", property: "read" },
    { modbus_address: "44640", description: "", property: "read" },
    { modbus_address: "44641", description: "", property: "read" },
    { modbus_address: "44642", description: "", property: "read" },
    { modbus_address: "44643", description: "", property: "read" },
    { modbus_address: "44644", description: "", property: "read" },
    { modbus_address: "44645", description: "", property: "read" },
    { modbus_address: "44646", description: "", property: "read" },
    { modbus_address: "44647", description: "", property: "read" },
    { modbus_address: "44680", description: "", property: "read" },
    { modbus_address: "44681", description: "", property: "read" },
    { modbus_address: "44682", description: "", property: "read" },
    { modbus_address: "44683", description: "", property: "read" },
    { modbus_address: "44684", description: "", property: "read" },
    { modbus_address: "44685", description: "", property: "read" },
    { modbus_address: "44686", description: "", property: "read" },
    { modbus_address: "44687", description: "", property: "read" },
    { modbus_address: "44720", description: "", property: "read" },
    { modbus_address: "44721", description: "", property: "read" },
    { modbus_address: "44722", description: "", property: "read" },
    { modbus_address: "44723", description: "", property: "read" },
    { modbus_address: "44724", description: "", property: "read" },
    { modbus_address: "44725", description: "", property: "read" },
    { modbus_address: "44726", description: "", property: "read" },
    { modbus_address: "44727", description: "", property: "read" },
    { modbus_address: "44800", description: "", property: "read" },
    { modbus_address: "44801", description: "", property: "read" },
    { modbus_address: "44802", description: "", property: "read" },
    { modbus_address: "44803", description: "", property: "read" },
    { modbus_address: "44820", description: "", property: "read" },
    { modbus_address: "44821", description: "", property: "read" },
    { modbus_address: "44822", description: "", property: "read" },
    { modbus_address: "44823", description: "", property: "read" },
    { modbus_address: "44840", description: "", property: "read" },
    { modbus_address: "44841", description: "", property: "read" },
    { modbus_address: "44842", description: "", property: "read" },
    { modbus_address: "44843", description: "", property: "read" },
    { modbus_address: "44860", description: "", property: "read" },
    { modbus_address: "44861", description: "", property: "read" },
    { modbus_address: "44862", description: "", property: "read" },
    { modbus_address: "44863", description: "", property: "read" },
    { modbus_address: "44880", description: "", property: "read" },
    { modbus_address: "44881", description: "", property: "read" },
    { modbus_address: "44882", description: "", property: "read" },
    { modbus_address: "44883", description: "", property: "read" },
    { modbus_address: "44900", description: "", property: "read" },
    { modbus_address: "44901", description: "", property: "read" },
    { modbus_address: "44902", description: "", property: "read" },
    { modbus_address: "44903", description: "", property: "read" },
    { modbus_address: "46060", description: "", property: "read" },
    { modbus_address: "46061", description: "", property: "read" },
    { modbus_address: "46062", description: "", property: "read" },
    { modbus_address: "46063", description: "", property: "read" },
    { modbus_address: "46070", description: "", property: "read" },
    { modbus_address: "46071", description: "", property: "read" },
    { modbus_address: "46072", description: "", property: "read" },
    { modbus_address: "46073", description: "", property: "read" },
  ],
};

module.exports = {
  deviceList,
  nutrient,
  activeList,
  emergency,
  readNutrient,
  readNutrientDataDigitalAndAnalog,
  supply,
};
